//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Floor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class master_FloorEntities : DbContext
    {
        public master_FloorEntities()
            : base("name=master_FloorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialPercent> MaterialPercent { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<PartnerImport> PartnerImport { get; set; }
        public virtual DbSet<PartnerName> PartnerName { get; set; }
        public virtual DbSet<Partnertype> Partnertype { get; set; }
        public virtual DbSet<productDesc> productDesc { get; set; }
        public virtual DbSet<ProductImport> ProductImport { get; set; }
        public virtual DbSet<ProductName> ProductName { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<street> street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
