//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Floor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int id { get; set; }
        public int partnerTypeId { get; set; }
        public int partnernameId { get; set; }
        public Nullable<int> locationId { get; set; }
        public int cityId { get; set; }
        public int streetId { get; set; }
        public int building { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int cityIndex { get; set; }
        public string iin { get; set; }
        public int rating { get; set; }
    
        public virtual City City { get; set; }
        public virtual Location Location { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        public virtual Partnertype Partnertype { get; set; }
        public virtual street street { get; set; }
    }
}
