//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Floor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerImport
    {
        public int id { get; set; }
        public int partnerId { get; set; }
        public int productId { get; set; }
        public int materialId { get; set; }
        public int productNameId { get; set; }
        public int quentity { get; set; }
        public System.DateTime saleDate { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
