//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Floor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImport
    {
        public int id { get; set; }
        public int productId { get; set; }
        public int nameOfProductId { get; set; }
        public int article { get; set; }
        public decimal minPrice { get; set; }
    
        public virtual ProductName ProductName { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
