//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Floor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productDesc
    {
        public int id { get; set; }
        public Nullable<int> name { get; set; }
        public Nullable<decimal> percentOnSale { get; set; }
    }
}
